### ISSUE TITLE
NullReferenceException when app goes to background

### ISSUE THREAD

**Issue by codeknox** [kerryjiang/WebSocket4Net#16]
Hey there, when my app is sent to background, usually I get this error.

{System.Windows.ApplicationUnhandledExceptionEventArgs}
    base: {System.Windows.ApplicationUnhandledExceptionEventArgs}
    _exception: {System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.Socket.ResetHandle()
   at System.Net.Sockets.SocketNotificationCallback.Paused(XPauseType pauseType)
   at System.Net.Sockets.SocketNotificationManager.Paused(XPauseType pauseType)
   at MS.Internal.Interop.SocketNotificationCallbackProxy.Paused(XPauseType pauseType)
   at MS.Internal.Interop.NotificationService.NotificationPaused(XPauseType pauseType)
   at MS.Internal.FrameworkCallbacks.NotificationPaused(UInt32 pauseType)}
    _handled: false
    ExceptionObject: {System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.Socket.ResetHandle()
   at System.Net.Sockets.SocketNotificationCallback.Paused(XPauseType pauseType)
   at System.Net.Sockets.SocketNotificationManager.Paused(XPauseType pauseType)
   at MS.Internal.Interop.SocketNotificationCallbackProxy.Paused(XPauseType pauseType)
   at MS.Internal.Interop.NotificationService.NotificationPaused(XPauseType pauseType)
   at MS.Internal.FrameworkCallbacks.NotificationPaused(UInt32 pauseType)}
    Handled: false

Here is the full stack trace:

```
Chat.WP8.DLL!Chat.WP8.App.Application_UnhandledException(object sender, System.Windows.ApplicationUnhandledExceptionEventArgs e) Line 155   C#
System.Windows.ni.dll!MS.Internal.Error.CallApplicationUEHandler(System.Exception e)    Unknown
System.Windows.ni.dll!MS.Internal.JoltHelper.OnUnhandledException(object sender, System.UnhandledExceptionEventArgs args)   Unknown
[Native to Managed Transition]  
System.Net.ni.dll!System.Net.Sockets.Socket.ResetHandle()   Unknown
System.Net.ni.dll!System.Net.Sockets.SocketNotificationCallback.Paused(System.Net.Sockets.XPauseType pauseType) Unknown
System.Net.ni.dll!System.Net.Sockets.SocketNotificationManager.Paused(System.Net.Sockets.XPauseType pauseType)  Unknown
System.Windows.ni.dll!MS.Internal.Interop.SocketNotificationCallbackProxy.Paused(MS.Internal.Interop.XPauseType pauseType)  Unknown
System.Windows.ni.dll!MS.Internal.Interop.NotificationService.NotificationPaused(MS.Internal.Interop.XPauseType pauseType)  Unknown
System.Windows.ni.dll!MS.Internal.FrameworkCallbacks.NotificationPaused(uint pauseType) Unknown
```

I've noticed you had a similar (same?) issue on CodePlex http://websocket4net.codeplex.com/discussions/436322 , but I could not comment there, as it needs a login.

Was that solved?
You asked about the thread, it's the main thread:

```
    3348    1   Main Thread Main Thread Chat.WP8.DLL!Chat.WP8.App.Application_UnhandledException    Normal
```

As there is no source code anywhere, I can't actually catch this, except on Application_UnhandledException.
Any idea?

Thanks
CodeKnox

**Comment by XiaosongLin** [comment]
@codeknox Hi, we also met this issue, could you please share more information about how to deal with this serious problem?   It happens frequently when the network situation bad then switch the app foreground/backgroud.

**Comment by codeknox** [comment]
I did exactly what  I wrote above your post.
