### ISSUE TITLE
The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by allmyfantasy** [kerryjiang/WebSocket4Net#169]
CoreCLR Version: 4.700.19.60701
.NET Core Version: 3.1.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at WebSocket4Net.Common.ArraySegmentList.DecodeMask(Byte[] mask, Int32 offset, Int32 length)
   at WebSocket4Net.WebSocketCommandInfo..ctor(IList`1 frames)
   at WebSocket4Net.Protocol.DraftHybi10DataReader.GetCommandInfo(Byte[] readBuffer, Int32 offset, Int32 length, Int32& left)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
   at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
   at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
   at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
   at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
   at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
   at SuperSocket.ClientEngine.AsyncTcpSession.StartReceive()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

**Comment by kerryjiang** [comment]
Please try WebSocket4Net latest beta release:
https://www.nuget.org/packages/WebSocket4Net/1.0.0-beta.4
