### ISSUE TITLE
NullReferenceException at WebSocket4Net.Protocol.DraftHybi10Processor.SendHandshake

### ISSUE THREAD

**Issue by Gdocal** [kerryjiang/WebSocket4Net#80]
System: Windows Serer 2012
version of library: 0.14.1.0
Description of library: WebSocket4Net for .NET 4.0/Mono 2.10+ 
Runtime version: v4.0.30319
My whole app crashed with this error, and I can't prevent this as I do not control thread which throws that exception.
Here is exception details, sorry there are no line numbers.
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at WebSocket4Net.Protocol.DraftHybi10Processor.SendHandshake(WebSocket4Net.WebSocket)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Security.SslState.FinishHandshake(System.Exception, System.Net.AsyncProtocolRequest)
   at System.Net.Security.SslState.WriteCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by kerryjiang** [comment]
Thanks, I did a fix for this issue just now.
https://github.com/kerryjiang/WebSocket4Net/commit/12146f0ec8cb3677904ad905ce19d33021482b2e

**Comment by kerryjiang** [comment]
I released a new version in nuget including this fix 0.15.0-beta8, please have a try.

**Comment by srborha** [comment]
Facing same issue of null pointer exception 

Library used : 
WebSocket4Net (0.15.2)
NETStandard.Library(2.0.3)
.NET standard 2.0 used

Exception !!! : [org.tizen.art-app] [2297] EXCEPTION Exception !!!: System.NullReferenceException: Object reference not set to an instance of an object.
   at WebSocket4Net.Protocol.DraftHybi10Processor.SendHandshake(WebSocket websocket)
   at WebSocket4Net.WebSocket.OnConnected()
   at WebSocket4Net.WebSocket.client_Connected(Object sender, EventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnConnected()
   at SuperSocket.ClientEngine.AsyncTcpSession.OnGetSocket(SocketAsyncEventArgs e)
   at SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   at SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.ConnectCompletionCallback(SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.ConnectOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.WriteOperation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
